name: Deploy nginx container and configuration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
          NAMECOM_USERNAME: ${{ secrets.NAMECOM_USERNAME }}
          NAMECOM_TOKEN: ${{ secrets.NAMECOM_TOKEN }}
        run: |    
          # Dateien kopieren
          scp -o StrictHostKeyChecking=no nginx.conf $SERVER_USER@$SERVER_IP:$APP_DIR/
          scp -o StrictHostKeyChecking=no docker-compose.yml $SERVER_USER@$SERVER_IP:$APP_DIR/
          scp -o StrictHostKeyChecking=no ssh-config-script.sh $SERVER_USER@$SERVER_IP:$APP_DIR/
          
          # Container neu starten
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            cd $APP_DIR &&
            chmod +x ./ssh-config-script.sh &&
          
            # Umgebungsvariablen in .env-Datei persistieren
            echo 'NAMECOM_USERNAME=$NAMECOM_USERNAME' > .env &&
            echo 'NAMECOM_TOKEN=$NAMECOM_TOKEN' >> .env &&
            chmod 600 .env &&
          
            # Cronjob pr端fen und nur hinzuf端gen wenn noch nicht vorhanden
            SCRIPT_PATH=\$(pwd)/ssh-config-script.sh &&
            CRON_CMD=\"0 2 * * * cd $APP_DIR && source .env && export NAMECOM_USERNAME NAMECOM_TOKEN && \$SCRIPT_PATH\" &&
          
            # Pr端fen ob Cronjob bereits existiert
            if ! crontab -l 2>/dev/null | grep -q \"ssh-config-script.sh\"; then
              echo \"F端ge Cronjob hinzu...\" &&
              (crontab -l 2>/dev/null; echo \"\$CRON_CMD\") | crontab -
            else
              echo \"Cronjob bereits vorhanden\"
            fi &&
          
            source .env && export NAMECOM_USERNAME NAMECOM_TOKEN && ./ssh-config-script.sh
          "